### PR TITLE
Add grantmakers/grantmakers.github.io & add comments.

### PR DESCRIPTION
**Pull request by parkr**
This repo houses some tiny scripts to run Jekyll `master` against some hand-picked websites once a day. The purpose of this is to promote & validate Jekyll's stability beyond unit & integration tests. More in the README.

@benbalter, are there any other sites you think we should test each night?

/cc @jekyll/stability

### CODE REVIEW

**Comment by DirtyF** [comment]
@parkr what about some popular theme like https://mmistakes.github.io/minimal-mistakes/ ?

**Comment by parkr** [comment]
@DirtyF Great idea!

**Comment by mattr-** [comment]
bootstrap's blog? https://github.com/twbs/bootstrap-blog

**Comment by mattr-** [comment]
this one might be good because it's non english: https://github.com/Gaohaoyang/gaohaoyang.github.io

**Comment by benbalter** [comment]
> are there any other sites you think we should test each night?

100% on board with the idea, would it make more sense to version them as submodules and/or make specific fixtures that exercise desired functionality, scale, etc.? I'd hate for me breaking my site to cause a Jekyll build to fail.

**Comment by parkr** [comment]
> I'd hate for me breaking my site to cause a Jekyll build to fail.

@benbalter Agreed, but I want this repo to be set-it-and-forget-it, using the latest of everything. I don't want to have to remember to come in here and upgrade the submodules. I'm willing to tolerate issues for sites (we can always remove sites from the list if they're becoming annoying).

**Comment by parkr** [comment]
Feel free to PR if you have other suggestions. There's probably a time limit imposed by Travis and I definitely don't want the list to exceed 10 sites. This is a great start for the long-term stability of Jekyll!

**Review by ghost — COMMENTED** [review]
xxx

**Pull request merged**
